### ISSUE TITLE
Can't figure out this error when running Symbioz.

### ISSUE THREAD

**Issue by imnotacrook** [Skinz3/Symbioz#12]
Hey guys, I'm pretty new to all of this and I've managed to get stuck attempting to get a dofus server up and running. I got my database all set up, but when I go to run Symbioz I get this error: http://imgur.com/THetRAi

I'm not sure if anybody can give me some insight on how to fix this, but if you can I'd greatly appreciate it. There's a strong chance that I'm too clueless to be able to accept any advice ,but if it's a simple fix then that would be great.

Thanks.

**Comment by nojo123** [comment]
Hi sir,
I had this error aswell the problem is is that you didnt run the sql-files in the appropiate order. I would suggest deleting your database. As i'm not at home yet I can't give you the order you should run them, but if i get home i will be able to tell you.

**Comment by nojo123** [comment]
Order of running SQL-files:
1. Symbioz.sql
2. Patch mapspositions.sql
3. Patch dungeonsids.sql
4. Patch guilds.sql
5. Alliances.sql
6. Patch alliances.sql
7. Patch MapTriggers.sql
8. Patch MapTriggers 2.sql

**Comment by imnotacrook** [comment]
Thank you very much. I had a friend assisting me with this process and I asked him if the order was causing that error. His response was "probably not" so I'm glad I came here to double check. I appreciate your quick response. :)

**Comment by nojo123** [comment]
Great it fixed you problem. If you have any other questions please ask them. :)
Also here is a little gift: https://mega.nz/#!9dcTGKaa!MebjgFw46moidnLjfJt1HJ4f-g2c2xN1cJKfm9mdQlc
These SQL's will give you shops at the Zaap in Bonta.

**Comment by imnotacrook** [comment]
Oh, that's great. Thank you very much for that. :)

**Comment by imnotacrook** [comment]
Hey, Nojo, I don't know if you'll happen to see this message now that this thread is closed but if you do I sent you a friend request on Skype. I have a  handful of quick questions for you that I don't want to bother this Issue Section with. If you happen to have the time to answer them, I'd be very grateful.

**Comment by Matspyder51** [comment]
I have regroup every Sql in one file now, when Skinz will accept the pull request

**Comment by nojo123** [comment]
Thanks Mat, this will make it alot eadier for new users. I have a little question though, would you be able to make more commands for the emu like: making a guild or showing character cell and map?

**Comment by nojo123** [comment]
Just saw that there already is a command to create a guild. What im currently only missing is the command to show my character mapid and cellid and the command to give my character characteristic points. Would you be able to implement this and for fun maybe godmode?

**Comment by Matspyder51** [comment]
For MapId and CellId, you just have to type /cellid or /mapid in the chat, it's by default implemented in Dofus Client, And for Characteristic Points, It's very easy, just need to find time to do it

**Comment by nojo123** [comment]
Thanks Matt, take the time you need. Would you be able to explain to me how to code commands or is this to difficult to explain?

**Comment by Matspyder51** [comment]
Done in the new Pull Request (.addcaracs and .god "Username")

And Doom Spell now work to for level 1 (SpellId = 415)
