### ISSUE TITLE
Problem with resources

### ISSUE THREAD

**Issue by sidneypp** [Skinz3/Symbioz#18]
Good people, I'm asking for forgiveness for my bad English, I'm using google translator to help me.
I'm trying to create a server for some friends to have fun with and I'm having a problem adding features to the map, things like trees, ores, fish in lakes, cereal, among others.
I would like to know if you have the possibility to do this on the Symbioz server, and if possible some help with adding those features on the map.

**Comment by Skinz3** [comment]
Yes, its possible, you need to manage the bdd. Im french btw ^^'
