### ISSUE TITLE
Unable to start AuthServer

### ISSUE THREAD

**Issue by TristanLemire** [Skinz3/Symbioz#24]
Hello i have a problem!

When I run symbioz.exe I have this error message ")) Error: Unable to start AuthServer! : (Une tentative d'accès à un socket de manière interdite par ses autorisations d'accès a été tentée)"

translation: "An attempted access to a socket in a way prohibited by its access permissions was attempted"

help me please ^^

**Comment by nojo123** [comment]
Hi!
You could try a different port by changing this in the config file (standard is port 443, just make sure you change the dofus config file to use this port aswell) and are you sure you gave it firewall permission?

Goodluck!

**Comment by TristanLemire** [comment]
Thank you! i change the port 443 to 6666 ^^

**Comment by nojo123** [comment]
Awesome, have fun! You do know that this project will probably not get any new updates? We can just hope that Skinz uploads his 2.40 version ;-).

**Comment by TristanLemire** [comment]
Yes I know ^ ^ but I start so it suits me for the moment.I can not seem to show weapons with the command ".item ****", the console tells me unknown object, for all weapons . And thanks for everything

**Comment by nojo123** [comment]
Thats right, weapons aren't included unfortunately.
