### ISSUE TITLE
[Help] Problem Login Symbioz 2.38

### ISSUE THREAD

**Issue by AinzGone** [Skinz3/Symbioz#27]
please help Client 2.38 from same file Symbioz 2.38 by Skinz

![2018-06-10 2](https://user-images.githubusercontent.com/40129307/41196923-ed199e1a-6c5d-11e8-9fa3-2e17827b60d7.png)
![2018-06-10 1](https://user-images.githubusercontent.com/40129307/41196924-f3d06324-6c5d-11e8-8b5e-e8d314d1d057.png)

**Comment by Skinz3** [comment]
In database, in account table, you need to set the Banned value, to False or True.

**Comment by AinzGone** [comment]
Thank you i found it in dozenofelite same your respond, the emulator is so nice, but just one thing the admin console window how i get the list of the commands ? I tried help/commandslist... didn't work

**Comment by Skinz3** [comment]
just put 'help' in the world server console.

**Comment by AinzGone** [comment]
Wonderful, can i get your email, or discord or something because Im planning to open server dofus private so i might need some coding and stuff so.. You know, can i get any

**Comment by Skinz3** [comment]
Sorry, im far from Dofus emulation right now ^^
