### ISSUE TITLE
Symbioz Error TimeOut

### ISSUE THREAD

**Issue by GuardianAngels** [Skinz3/Symbioz#4]
Hi, I have a little problem Symbioz Emulator during initialization
he loads the tables, when he load maps, he says a timeout error of MySql
(SQL on my vps)
if you have an idea of the cause and you can tell me why?
a screenshot of this error : http://prntscr.com/az2ggm

Good day.

**Comment by Skinz3** [comment]
Its probably your connection speed, did you host you database in 'localhost'?

Tu es français peut être?

**Comment by GuardianAngels** [comment]
Je suis francais oui, j'ai essayé de mettre l'émulateur en localhost sur mon vps (debian) mais il ne trouve pas le fichier d2i, il y a un / de windows inversé a la fin

**Comment by GuardianAngels** [comment]
Si jamais voici un screen de l'erreur : http://prnt.sc/azszr7
