### ISSUE TITLE
Bug in fight ending when we are in a group

### ISSUE THREAD

**Issue by DarkRedFish** [Skinz3/Symbioz#5]
Hi,

There is a problem with the end of a fight when I have two users in a group, fight is never ending, it's stuck like this (see image below)

The problem don't exist in solo or if the two users are in the fight but not in group...

Thank you if you can have a look at it.

![image](https://cloud.githubusercontent.com/assets/8996095/14954880/134b1a6e-1076-11e6-992e-9286714ff196.png)

**Comment by DarkRedFish** [comment]
Pourquoi tu as close ?...

**Comment by Skinz3** [comment]
C'est un problème connu, il a été résolu sur la 2.34 ;)
