### ISSUE TITLE
No update for half a month

### ISSUE THREAD

**Issue by DoctorFrickle** [Skinz3/Symbioz#6]
Give us an update?(if your still even working on it)

**Comment by nojo123** [comment]
Maybe he is working on a major update and he needs his time. So I don't think we should be asking for updates as he already did an amazing job. Lets just wait and see and hopefully he will be back in some time.

**Comment by Skinz3** [comment]
Me and Mat are working hard on Symbioz, but on a 2.34 version, so we fix every bugs we can found In game dont worry, u'll have news soon

**Comment by DoctorFrickle** [comment]
Cool, thanks for the info :D

**Comment by leonardo-spy** [comment]
because it will not let the public ? I know it's hard to stay without motivation but come on, do not let not private u.u plzzz

**Comment by leonardo-spy** [comment]
and If by chance... i could help?

**Comment by simonswinslam** [comment]
Emu private or update stopped??

**Comment by nojo123** [comment]
Hopefully you will still release them for the public, if not that would be a pitty :/.
Non the less u did a great job.
