### ISSUE TITLE
 Compilation errors

### ISSUE THREAD

**Issue by leonardo-spy** [Skinz3/Symbioz#7]
Hello, i am leonardonaruto
when I will compile of the following errors :
AFKMessage is missing
UnauthorizedCreationGiveEmotes  is missing.
and it will take you long to fix the effects (ex: Eff_AddCriticalDamageBonus is not handled)?
u.u :3 :+1:

**Comment by simonswinslam** [comment]
He s doing the most important things first .the effects come later

**Comment by leonardo-spy** [comment]
because it will not let the public (2.34) ? I know it's hard to stay without motivation but come on, do not let not private u.u plzzz

**Comment by leonardo-spy** [comment]
and If by chance... i could help?

**Comment by simonswinslam** [comment]
people only think about money these days .I'm sure the emulator will be private in no time.I wish.Free emu you can always dream

**Comment by DoctorFrickle** [comment]
skinz is rip, 2004-2016, may he rest in peace

**Comment by leonardo-spy** [comment]
by the way I already repaired the compilation errors

**Comment by leonardo-spy** [comment]
skinz is rip, 2004-2016, may he rest in peace
