### ISSUE TITLE
I can't get past the login screen.

### ISSUE THREAD

**Issue by Twdwd** [Skinz3/Symbioz#9]
Whenever I try to login it says "New client connected!", "[Send] HelloGameMessage" after that the dofus client keeps trying to connect http://puu.sh/r7ETv/783f8020dc.jpg

How do I fix this?

**Comment by nojo123** [comment]
Could u send a screenshot of your CMD window? One problem could be port forwarding, another could be that you didn't put your local ip on all necessary spots in the config file.

**Comment by Twdwd** [comment]
I fixed it! :) I only have 1 other problem, when I create another character he get's the eniripsa spells, how does one fix it?

**Comment by nojo123** [comment]
You say "another" does that mean that you created an Eniripsa before you created a new character and did this bug then occur?

**Comment by Twdwd** [comment]
Nevermind, I fixed it! :)
I got another question, why do the markers on the ground to leave the map not work? Like when I'm inside the bank I can't get out.

**Comment by nojo123** [comment]
Its just not complete, you can do it yourself. You have to add them to the map interactives in your database. If you want you can add me on Skype and we can take a look at it together on one of the following days as I'm currently not on my PC with the files.

**Comment by Twdwd** [comment]
Sure, my skype is "ret2lib"! :)

**Comment by nojo123** [comment]
Alrighty, I added you. Btw, you know that Skinz won't update the server files? So any bug fixes we have to do ourself. :P

**Comment by Twdwd** [comment]
Oh haha :)
